version: '2.0'
services:
  db-megawatts:
    build:
      context: ./docker
      dockerfile: Dockerfile-db

  sitemanagement:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-megawatts
    command: ./run_server.sh
    entrypoint: ./wait-for-db.sh db-megawatts:5432
    ports:
      - "8002:8002"
    links:
      - db-megawatts
    depends_on:
      - db-megawatts
    volumes:
      - ./reports/:/opt/megawatts/reports

  sitemanagement-migrations:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-megawatts
    command: ./migrate-load-data.sh
    entrypoint: ./wait-for-db.sh db-megawatts:5432
    links:
      - db-megawatts
      - sitemanagement
    depends_on:
      - db-megawatts
      - sitemanagement